### ISSUE TITLE
Error thrown for non-promise tests

### ISSUE THREAD

**Issue by chrisdothtml** [jprichardson/tape-promise#18]
Tests that are not promises (or async) throw with the following error:

```
not ok 2 test exited without ending
  ---
    operator: fail
    at: process.<anonymous> ([...]/node_modules/tape/index.js:90:19)
    stack: |-
      Error: test exited without ending
          at Test.assert [as _assert] ([...]/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] ([...]/node_modules/tape/lib/test.js:77:32)
          at Test.fail ([...]/node_modules/tape/lib/test.js:319:10)
          at Test.bound [as fail] ([...]/node_modules/tape/lib/test.js:77:32)
          at Test._exit ([...]/node_modules/tape/lib/test.js:191:14)
          at Test.bound [as _exit] ([...]/node_modules/tape/lib/test.js:77:32)
          at process.<anonymous> ([...]/node_modules/tape/index.js:90:19)
          at process.emit (events.js:197:13)
```

Repro repo [here](https://github.com/chrisdothtml/tape-promise-18)

**Comment by RyanZim** [comment]
You need to explicitly call `t.end()`.

**Comment by chrisdothtml** [comment]
🤦‍♂️ oof. Thanks, lol

**Comment by shikhars371** [comment]
new issue ,

test('can mount ddatabases', async t => {
  const store = new Basestore(ram)
  store.ready(onready)

  function onready () {
    const drive = create({ basestore: store })
    var base = store.get()

    drive.ready(err => {
      t.error(err, 'no error')
      base.ready(err => {
        t.error(err, 'no error')
        base.append('hello', err => {
          t.error(err, 'no error')
          return onappend(drive, base)
        })
      })
    })
  }

  function onappend (drive, base) {
    drive.mount('/a', base.key, { ddatabase: true }, err => {
      t.error(err, 'no error')
      drive.readFile('/a', (err, contents) => {
        t.error(err, 'no error')
        t.same(contents, Buffer.from('hello'))
        t.end()
      })
    })
  }
})

getting error 
test exited without ending: can mount ddatabases
  ---
    operator: fail
    at: process.<anonymous> (/Users/shikharsrivastava/Desktop/new_libs/ddrive/node_modules/tape/index.js:83:19)
    stack: |-
      Error: test exited without ending: can mount ddatabases
          at Test.assert [as _assert] (/Users/shikharsrivastava/Desktop/new_libs/ddrive/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/Users/shikharsrivastava/Desktop/new_libs/ddrive/node_modules/tape/lib/test.js:80:32)
          at Test.fail (/Users/shikharsrivastava/Desktop/new_libs/ddrive/node_modules/tape/lib/test.js:322:10)
          at Test.bound [as fail] (/Users/shikharsrivastava/Desktop/new_libs/ddrive/node_modules/tape/lib/test.js:80:32)
          at Test._exit (/Users/shikharsrivastava/Desktop/new_libs/ddrive/node_modules/tape/lib/test.js:191:14)
          at Test.bound [as _exit] (/Users/shikharsrivastava/Desktop/new_libs/ddrive/node_modules/tape/lib/test.js:80:32)
          at process.<anonymous> (/Users/shikharsrivastava/Desktop/new_libs/ddrive/node_modules/tape/index.js:83:19)
          at process.emit (events.js:196:13)
  ...

**Comment by RyanZim** [comment]
You're using an async function when your code uses callbacks; remove `async`. Also, in the future, please don't bump old issues; open a new issue instead.
