### ISSUE TITLE
possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by aliatsis** [jprichardson/tape-promise#3]
Getting the following error. Might need to `emitter.setMaxListeners(0)` at the beginning of a test and possibly reset it to the original value when the test completes.

```
(node) warning: possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at process.once (events.js:265:8)
    at Test.<anonymous> (/Users/anthonyliatsis/projects/auth/node_modules/tape-promise/index.es5.js:18:15)
    at Test.bound [as _cb] (/Users/anthonyliatsis/projects/auth/node_modules/tape/lib/test.js:61:32)
    at Test.run (/Users/anthonyliatsis/projects/auth/node_modules/tape/lib/test.js:80:10)
    at Test.bound [as run] (/Users/anthonyliatsis/projects/auth/node_modules/tape/lib/test.js:61:32)
    at Immediate.next [as _onImmediate] (/Users/anthonyliatsis/projects/auth/node_modules/tape/lib/results.js:70:15)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by jprichardson** [comment]
Does setting `process.setMaxListeners(0)` fix your problem?

**Comment by jprichardson** [comment]
Could you share the test snippet that is causing this? Thanks.

**Comment by aliatsis** [comment]
process.setMaxListeners(0) fixed it
